### ISSUE TITLE
Failure during startup: NPE for internal port bindings

### ISSUE THREAD

**Issue by vierbergenlars** [xenit-eu/nuntio#8]
```
2022-02-23 17:28:56.968 ERROR 1 --- [           main] e.x.n.i.s.NuntioApplicationNormalStartup : Failed to register services at startup. Waiting for registration to complete before continuing.
java.lang.NullPointerException: null
	at eu.xenit.nuntio.platform.docker.config.parser.InspectContainerMetadata.getInternalPortBindings(InspectContainerMetadata.java:25) ~[nuntio-platform-docker-0.1.0.jar!/:na]
	at eu.xenit.nuntio.platform.docker.config.parser.RegistratorCompatibleParser.toServiceConfigurations(RegistratorCompatibleParser.java:35) ~[nuntio-platform-docker-0.1.0.jar!/:na]
	at eu.xenit.nuntio.platform.docker.config.parser.SwitchingServiceConfigurationParser.toServiceConfigurations(SwitchingServiceConfigurationParser.java:17) ~[nuntio-platform-docker-0.1.0.jar!/:na]
	at eu.xenit.nuntio.platform.docker.DockerContainerServiceDescriptionFactory.createConfiguration(DockerContainerServiceDescriptionFactory.java:45) ~[nuntio-platform-docker-0.1.0.jar!/:na]
	at eu.xenit.nuntio.platform.docker.DockerContainerServiceDescriptionFactory.createConfiguration(DockerContainerServiceDescriptionFactory.java:32) ~[nuntio-platform-docker-0.1.0.jar!/:na]
	at eu.xenit.nuntio.platform.docker.DockerContainerServiceDescriptionFactory.createServiceDescription(DockerContainerServiceDescriptionFactory.java:27) ~[nuntio-platform-docker-0.1.0.jar!/:na]
	at eu.xenit.nuntio.platform.docker.DockerPlatform.find(DockerPlatform.java:49) ~[nuntio-platform-docker-0.1.0.jar!/:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:na]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:na]
	at eu.xenit.nuntio.platform.docker.DockerPlatform.findAll(DockerPlatform.java:38) ~[nuntio-platform-docker-0.1.0.jar!/:na]
	at eu.xenit.nuntio.engine.PlatformServicesSynchronizer.syncServices(PlatformServicesSynchronizer.java:26) ~[nuntio-engine-0.1.0.jar!/:na]
	at eu.xenit.nuntio.integration.startup.NuntioApplicationNormalStartup.lambda$run$1(NuntioApplicationNormalStartup.java:32) ~[nuntio-integration-0.1.0.jar!/:na]
	at io.github.resilience4j.retry.Retry.lambda$decorateSupplier$2(Retry.java:213) ~[resilience4j-retry-1.7.1.jar!/:1.7.1]
	at io.github.resilience4j.retry.Retry.executeSupplier(Retry.java:430) ~[resilience4j-retry-1.7.1.jar!/:1.7.1]
	at eu.xenit.nuntio.integration.startup.NuntioApplicationNormalStartup.run(NuntioApplicationNormalStartup.java:29) ~[nuntio-integration-0.1.0.jar!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782) ~[spring-boot-2.5.4.jar!/:2.5.4]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772) ~[spring-boot-2.5.4.jar!/:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345) ~[spring-boot-2.5.4.jar!/:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.4.jar!/:2.5.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.4.jar!/:2.5.4]
	at eu.xenit.nuntio.app.NuntioCoreApplication.main(NuntioCoreApplication.java:19) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[nuntio-app-0.1.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[nuntio-app-0.1.0.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[nuntio-app-0.1.0.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[nuntio-app-0.1.0.jar:na]
```

**Comment by vierbergenlars** [comment]
This can happen for containers that have been created or are restarting, then `Ports` is null.

```
{
  "Id": "8c95bb5a9eeded36523c6f83bb6e2c02dd48278e0c07190a596552ff9b5f1340",
  "Created": "2021-07-06T07:56:41.964131384Z",
  "Path": "/docker-entrypoint.sh",
  "Args": [
    "-f",
    "/etc/logstash/conf.d/logstash.conf"
  ],
  "State": {
    "Status": "created",
    "Running": false,
    "Paused": false,
    "Restarting": false,
    "OOMKilled": false,
    "Dead": false,
    "Pid": 0,
    "ExitCode": 128,
    "Error": "driver failed programming external connectivity on endpoint mon-02_logstash (5525e18448e70dfdc229b27594953554f9b1190e9c5123f8676b1138376189eb): Bind for 0.0.0.0:514 failed: port is already allocated",
    "StartedAt": "0001-01-01T00:00:00Z",
    "FinishedAt": "0001-01-01T00:00:00Z"
  },
  "Image": "sha256:946621bebaabbb3c778c405cf83446c174fb8add0439a0aa4a001d3f80017301",
  "ResolvConfPath": "/var/lib/docker-latest/containers/8c95bb5a9eeded36523c6f83bb6e2c02dd48278e0c07190a596552ff9b5f1340/resolv.conf",
  "HostnamePath": "",
  "HostsPath": "/var/lib/docker-latest/containers/8c95bb5a9eeded36523c6f83bb6e2c02dd48278e0c07190a596552ff9b5f1340/hosts",
  "LogPath": "",
  "Name": "/mon-02_logstash",
  "RestartCount": 0,
  "Driver": "devicemapper",
  "MountLabel": "",
  "ProcessLabel": "",
  "AppArmorProfile": "",
  "ExecIDs": null,
  "HostConfig": {
    "Binds": [
      "/opt/docker-compose/central-monitoring/logstash/tls:/etc/logstash/conf.d/tls:rw",
      "/opt/docker-compose/central-monitoring/logstash/config/patterns:/etc/logstash/conf.d/patterns:rw",
      "/var/run/docker.sock:/var/run/docker.sock:ro",
      "/opt/docker-compose/central-monitoring/logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf:rw"
    ],
    "ContainerIDFile": "",
    "LogConfig": {
      "Type": "journald",
      "Config": {}
    },
    "NetworkMode": "dockercompose_default",
    "PortBindings": {
      "514/tcp": [
        {
          "HostIp": "",
          "HostPort": "514"
        }
      ],
      "514/udp": [
        {
          "HostIp": "",
          "HostPort": "514"
        }
      ]
    },
    "RestartPolicy": {
      "Name": "",
      "MaximumRetryCount": 0
    },
    "AutoRemove": false,
    "VolumeDriver": "",
    "VolumesFrom": [],
    "CapAdd": null,
    "CapDrop": null,
    "Dns": [],
    "DnsOptions": [],
    "DnsSearch": [],
    "ExtraHosts": [
      "nphosting-02:10.88.100.144",
      "hosting-02:10.88.100.146",
      "hosting-03.local.xenit.eu:10.88.100.154",
      "hosting-03:10.88.100.154",
      "swarm-controller-01:10.88.10.134",
      "swarm-controller-11:10.99.10.134",
      "cgw-01:10.88.10.137",
      "cgw-02:10.88.10.138",
      "cgw-05:10.88.10.141",
      "devel-02:10.88.50.149",
      "athena:10.88.10.110",
      "aurora:10.88.10.103",
      "rome:10.88.10.109",
      "sparta:10.88.10.108",
      "atlanta:10.99.10.190",
      "infra-05:10.88.10.145",
      "mon-02:10.88.10.107",
      "infra-06:10.88.10.173",
      "infra-07:10.88.10.169",
      "sbx-oup-dam:10.88.60.166",
      "nphosting-03:10.88.100.172",
      "nphosting-04:10.88.100.177",
      "hosting-04:10.88.100.174",
      "hosting-05:10.88.100.175",
      "hosting-06:10.88.100.176",
      "babylon:10.88.10.113"
    ],
    "GroupAdd": null,
    "IpcMode": "",
    "Cgroup": "",
    "Links": null,
    "OomScoreAdj": 0,
    "PidMode": "",
    "Privileged": false,
    "PublishAllPorts": false,
    "ReadonlyRootfs": false,
    "SecurityOpt": null,
    "UTSMode": "",
    "UsernsMode": "",
    "ShmSize": 67108864,
    "Runtime": "docker-runc",
    "ConsoleSize": [
      0,
      0
    ],
    "Isolation": "",
    "CpuShares": 0,
    "Memory": 0,
    "NanoCpus": 0,
    "CgroupParent": "",
    "BlkioWeight": 0,
    "BlkioWeightDevice": null,
    "BlkioDeviceReadBps": null,
    "BlkioDeviceWriteBps": null,
    "BlkioDeviceReadIOps": null,
    "BlkioDeviceWriteIOps": null,
    "CpuPeriod": 0,
    "CpuQuota": 0,
    "CpuRealtimePeriod": 0,
    "CpuRealtimeRuntime": 0,
    "CpusetCpus": "",
    "CpusetMems": "",
    "Devices": null,
    "DiskQuota": 0,
    "KernelMemory": 0,
    "MemoryReservation": 0,
    "MemorySwap": 0,
    "MemorySwappiness": -1,
    "OomKillDisable": false,
    "PidsLimit": 0,
    "Ulimits": null,
    "CpuCount": 0,
    "CpuPercent": 0,
    "IOMaximumIOps": 0,
    "IOMaximumBandwidth": 0
  },
  "GraphDriver": {
    "Name": "devicemapper",
    "Data": {
      "DeviceId": "788",
      "DeviceName": "docker-253:2-1123-9f8221e116da7faac18c0585051fe374a8d9d1d3461d8eb17ed73e4d75c7d15a",
      "DeviceSize": "10737418240"
    }
  },
  "Mounts": [
    {
      "Type": "bind",
      "Source": "/opt/docker-compose/central-monitoring/logstash/logstash.conf",
      "Destination": "/etc/logstash/conf.d/logstash.conf",
      "Mode": "rw",
      "RW": true,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "/opt/docker-compose/central-monitoring/logstash/config/patterns",
      "Destination": "/etc/logstash/conf.d/patterns",
      "Mode": "rw",
      "RW": true,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "/opt/docker-compose/central-monitoring/logstash/tls",
      "Destination": "/etc/logstash/conf.d/tls",
      "Mode": "rw",
      "RW": true,
      "Propagation": "rprivate"
    },
    {
      "Type": "bind",
      "Source": "/var/run/docker.sock",
      "Destination": "/var/run/docker.sock",
      "Mode": "ro",
      "RW": false,
      "Propagation": "rprivate"
    }
  ],
  "Config": {
    "Hostname": "8c95bb5a9eed",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "ExposedPorts": {
      "514/tcp": {},
      "514/udp": {}
    },
    "Tty": true,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [
      "SERVICE_NAME=logstash",
      "SERVICE_TAGS=infra",
      "PATH=/opt/logstash/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "GOSU_VERSION=1.7",
      "LOGSTASH_MAJOR=2.4",
      "LOGSTASH_VERSION=1:2.4.0-1"
    ],
    "Cmd": [
      "-f",
      "/etc/logstash/conf.d/logstash.conf"
    ],
    "ArgsEscaped": true,
    "Image": "hub.xenit.eu/public/logstash:2.3-5",
    "Volumes": {
      "/etc/logstash/conf.d/logstash.conf": {},
      "/etc/logstash/conf.d/patterns": {},
      "/etc/logstash/conf.d/tls": {},
      "/var/run/docker.sock": {}
    },
    "WorkingDir": "",
    "Entrypoint": [
      "/docker-entrypoint.sh"
    ],
    "OnBuild": null,
    "Labels": {
      "com.docker.compose.config-hash": "6c149a6231628680057c220a17ffe35c97ed570d2741c8beee293613e1fa8d94",
      "com.docker.compose.container-number": "1",
      "com.docker.compose.oneoff": "False",
      "com.docker.compose.project": "docker-compose",
      "com.docker.compose.service": "monitor-logstash",
      "com.docker.compose.version": "1.21.2"
    }
  },
  "NetworkSettings": {
    "Bridge": "",
    "SandboxID": "a6912ab0b25942b409e2a0ce8325ba4cfe4505b260ee3453ffb533f0f71bef21",
    "HairpinMode": false,
    "LinkLocalIPv6Address": "",
    "LinkLocalIPv6PrefixLen": 0,
    "Ports": null,
    "SandboxKey": "/var/run/docker/netns/a6912ab0b259",
    "SecondaryIPAddresses": null,
    "SecondaryIPv6Addresses": null,
    "EndpointID": "",
    "Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "IPAddress": "",
    "IPPrefixLen": 0,
    "IPv6Gateway": "",
    "MacAddress": "",
    "Networks": {
      "dockercompose_default": {
        "IPAMConfig": null,
        "Links": null,
        "Aliases": [
          "monitor-logstash",
          "8c95bb5a9eed"
        ],
        "NetworkID": "5a7fe1e46226c50f281c5b4556ab03596faa889c8ce39ee2084158222061a037",
        "EndpointID": "",
        "Gateway": "",
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "MacAddress": ""
      }
    }
  }
}
```
